import { Activity } from '../types/activity';
import { ScheduleTemplate } from '../types/template';
import { UserStreak } from '../types/streak';
import { getTodayDateString, shiftDate } from './dateUtils';

export function getInitialActivities(): Activity[] {
  const today = getTodayDateString();
  const yesterday = shiftDate(today, -1);
  const tomorrow = shiftDate(today, 1);

  return [
    // Today's activities
    {
      id: 'act-1',
      date: today,
      title: 'React Development & System Architecture',
      category: 'study',
      startTime: '09:00',
      durationMinutes: 120,
      priority: 'high',
      energyLevel: 'high',
      preferredTime: 'morning',
      location: 'Home Office',
      notes: 'Focus on timeline drag-and-drop state machine and modular components.',
      isCompleted: true,
      completedAt: `${today}T11:00:00Z`,
      isFixedTime: false,
      focusMinutesLogged: 110,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-2',
      date: today,
      title: 'Morning Break & Pour-Over Coffee',
      category: 'rest',
      startTime: '11:00',
      durationMinutes: 30,
      priority: 'low',
      energyLevel: 'low',
      preferredTime: 'morning',
      isCompleted: true,
      completedAt: `${today}T11:30:00Z`,
      isFixedTime: false,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-3',
      date: today,
      title: 'DayWeave Core Engine Implementation',
      category: 'work',
      startTime: '11:30',
      durationMinutes: 120,
      priority: 'high',
      energyLevel: 'high',
      preferredTime: 'morning',
      notes: 'Deterministic scheduling algorithm and conflict detection module.',
      isCompleted: true,
      completedAt: `${today}T13:30:00Z`,
      isFixedTime: true,
      focusMinutesLogged: 120,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-4',
      date: today,
      title: 'Nutritious Lunch & Walk Outside',
      category: 'health',
      startTime: '13:30',
      durationMinutes: 60,
      priority: 'medium',
      energyLevel: 'low',
      preferredTime: 'afternoon',
      isCompleted: true,
      completedAt: `${today}T14:30:00Z`,
      isFixedTime: true,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-5',
      date: today,
      title: 'Strength Training & Cardio Workout',
      category: 'health',
      startTime: '14:30',
      durationMinutes: 60,
      priority: 'medium',
      energyLevel: 'high',
      preferredTime: 'afternoon',
      location: 'Athletic Center',
      notes: 'Heavy compound lifts + 15 min mobility stretches.',
      isCompleted: true,
      completedAt: `${today}T15:30:00Z`,
      isFixedTime: false,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-6',
      date: today,
      title: 'Client Review & Feedback Session',
      category: 'work',
      startTime: '16:00',
      durationMinutes: 75,
      priority: 'high',
      energyLevel: 'medium',
      preferredTime: 'afternoon',
      location: 'Google Meet',
      notes: 'Demonstrate responsive timeline and deterministic planner.',
      isCompleted: true,
      isFixedTime: true,
      focusMinutesLogged: 75,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-7',
      date: today,
      title: 'Reading Clean Architecture & Notes',
      category: 'study',
      startTime: '18:00',
      durationMinutes: 45,
      priority: 'medium',
      energyLevel: 'medium',
      preferredTime: 'evening',
      notes: 'Read chapter 4 and outline component boundaries.',
      isCompleted: false,
      isFixedTime: false,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-8',
      date: today,
      title: 'Dinner & Quality Time with Friends',
      category: 'social',
      startTime: '19:30',
      durationMinutes: 90,
      priority: 'high',
      energyLevel: 'low',
      preferredTime: 'evening',
      location: 'Downtown Bistro',
      isCompleted: false,
      isFixedTime: true,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },

    // Yesterday's sample
    {
      id: 'act-y1',
      date: yesterday,
      title: 'UI Design System & Tokens Setup',
      category: 'work',
      startTime: '09:30',
      durationMinutes: 180,
      priority: 'high',
      energyLevel: 'high',
      isCompleted: true,
      focusMinutesLogged: 160,
      isFixedTime: false,
      createdAt: `${yesterday}T08:00:00Z`,
      updatedAt: `${yesterday}T08:00:00Z`,
    },
    {
      id: 'act-y2',
      date: yesterday,
      title: 'Gym & Core Routine',
      category: 'health',
      startTime: '14:00',
      durationMinutes: 60,
      priority: 'medium',
      energyLevel: 'high',
      isCompleted: true,
      isFixedTime: false,
      createdAt: `${yesterday}T08:00:00Z`,
      updatedAt: `${yesterday}T08:00:00Z`,
    },

    // Tomorrow's sample
    {
      id: 'act-t1',
      date: tomorrow,
      title: 'TypeScript Performance Audit',
      category: 'study',
      startTime: '09:00',
      durationMinutes: 120,
      priority: 'high',
      energyLevel: 'high',
      isCompleted: false,
      isFixedTime: false,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-t2',
      date: tomorrow,
      title: 'Sprint Planning & Backlog Grooming',
      category: 'work',
      startTime: '11:30',
      durationMinutes: 90,
      priority: 'medium',
      energyLevel: 'medium',
      isCompleted: false,
      isFixedTime: true,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
    {
      id: 'act-t3',
      date: tomorrow,
      title: 'Evening Run & Mobility',
      category: 'health',
      startTime: '17:30',
      durationMinutes: 45,
      priority: 'medium',
      energyLevel: 'high',
      isCompleted: false,
      isFixedTime: false,
      createdAt: `${today}T08:00:00Z`,
      updatedAt: `${today}T08:00:00Z`,
    },
  ];
}

export const INITIAL_TEMPLATES: ScheduleTemplate[] = [
  {
    id: 'tmpl-1',
    title: 'Deep Work Day',
    description: 'Focused 4-hour morning deep work blocks with built-in afternoon gym and recovery.',
    icon: 'Brain',
    tag: 'Productivity',
    totalPlannedMinutes: 420,
    activitiesCount: 5,
    createdAt: '2026-09-01T00:00:00Z',
    activities: [
      {
        id: 't-act-1',
        title: 'Deep Coding / Technical Writing',
        category: 'work',
        startTime: '09:00',
        durationMinutes: 150,
        priority: 'high',
        energyLevel: 'high',
        notes: 'Zero distractions, full focus.',
      },
      {
        id: 't-act-2',
        title: 'Recharging Coffee Break',
        category: 'rest',
        startTime: '11:30',
        durationMinutes: 30,
        priority: 'low',
        energyLevel: 'low',
      },
      {
        id: 't-act-3',
        title: 'Architecture Review & Email Dispatch',
        category: 'work',
        startTime: '12:00',
        durationMinutes: 60,
        priority: 'medium',
        energyLevel: 'medium',
      },
      {
        id: 't-act-4',
        title: 'Healthy Lunch & Sunlight Walk',
        category: 'health',
        startTime: '13:00',
        durationMinutes: 60,
        priority: 'medium',
        energyLevel: 'low',
      },
      {
        id: 't-act-5',
        title: 'Strength Training Workout',
        category: 'health',
        startTime: '15:00',
        durationMinutes: 75,
        priority: 'high',
        energyLevel: 'high',
      },
    ],
  },
  {
    id: 'tmpl-2',
    title: 'Study & Course Mastery',
    description: 'Structured intervals for reading, synthesis, practice problems, and reflection.',
    icon: 'GraduationCap',
    tag: 'Learning',
    totalPlannedMinutes: 360,
    activitiesCount: 5,
    createdAt: '2026-09-02T00:00:00Z',
    activities: [
      {
        id: 't-act-6',
        title: 'Course Lectures & Deep Note Taking',
        category: 'study',
        startTime: '09:30',
        durationMinutes: 120,
        priority: 'high',
        energyLevel: 'high',
      },
      {
        id: 't-act-7',
        title: 'Mindful Break & Stretch',
        category: 'rest',
        startTime: '11:30',
        durationMinutes: 30,
        priority: 'low',
        energyLevel: 'low',
      },
      {
        id: 't-act-8',
        title: 'Hands-on Practice & Exercises',
        category: 'study',
        startTime: '12:00',
        durationMinutes: 90,
        priority: 'high',
        energyLevel: 'high',
      },
      {
        id: 't-act-9',
        title: 'Lunch & Relax',
        category: 'health',
        startTime: '13:30',
        durationMinutes: 60,
        priority: 'medium',
        energyLevel: 'low',
      },
      {
        id: 't-act-10',
        title: 'Flashcards & Concept Review',
        category: 'study',
        startTime: '15:00',
        durationMinutes: 60,
        priority: 'medium',
        energyLevel: 'medium',
      },
    ],
  },
  {
    id: 'tmpl-3',
    title: 'Weekend Reset & Wellness',
    description: 'Gentle flow with morning outdoor activity, personal projects, and social evening.',
    icon: 'Sun',
    tag: 'Restoration',
    totalPlannedMinutes: 300,
    activitiesCount: 4,
    createdAt: '2026-09-03T00:00:00Z',
    activities: [
      {
        id: 't-act-11',
        title: 'Morning Trail Hike or Jog',
        category: 'health',
        startTime: '09:00',
        durationMinutes: 90,
        priority: 'medium',
        energyLevel: 'high',
      },
      {
        id: 't-act-12',
        title: 'Home Organizing & Meal Prep',
        category: 'personal',
        startTime: '11:30',
        durationMinutes: 90,
        priority: 'medium',
        energyLevel: 'low',
      },
      {
        id: 't-act-13',
        title: 'Casual Reading / Creative Hobby',
        category: 'entertainment',
        startTime: '14:30',
        durationMinutes: 60,
        priority: 'low',
        energyLevel: 'low',
      },
      {
        id: 't-act-14',
        title: 'Dinner with Friends',
        category: 'social',
        startTime: '18:30',
        durationMinutes: 120,
        priority: 'high',
        energyLevel: 'low',
      },
    ],
  },
];

export const INITIAL_STREAK: UserStreak = {
  currentStreakDays: 7,
  longestStreakDays: 14,
  totalCompletedActivities: 48,
  totalFocusSessions: 22,
  totalFocusMinutes: 1140,
  lastActiveDate: getTodayDateString(),
  achievements: [
    {
      id: 'first_plan',
      title: 'First Planned Day',
      description: 'Structured your day with intentional time blocks.',
      icon: 'CalendarCheck',
      isUnlocked: true,
      unlockedAt: '2026-09-16T10:00:00Z',
      progress: 100,
      targetCount: 1,
      currentCount: 1,
    },
    {
      id: 'streak_7',
      title: '7-Day Streak',
      description: 'Consistently planned and executed your schedule for 7 days.',
      icon: 'Flame',
      isUnlocked: true,
      unlockedAt: '2026-09-23T00:00:00Z',
      progress: 100,
      targetCount: 7,
      currentCount: 7,
    },
    {
      id: 'focus_10',
      title: '10 Focus Sessions',
      description: 'Completed 10 deep focus timer sessions without distraction.',
      icon: 'Timer',
      isUnlocked: true,
      unlockedAt: '2026-09-20T15:00:00Z',
      progress: 100,
      targetCount: 10,
      currentCount: 22,
    },
    {
      id: 'century_club',
      title: 'Century Club',
      description: 'Complete 100 planned activities.',
      icon: 'Trophy',
      isUnlocked: false,
      progress: 48,
      targetCount: 100,
      currentCount: 48,
    },
  ],
};
